version: '3.8'

services:
  auth-api:
    build:
      context: ./backend/auth-api
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - DB_CONN_STRING=postgres://postgres:saberviagens@postgres:5432/auth_db?sslmode=disable

  orders-api:
    build:
      context: ./backend/orders-api
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    environment:
      - DB_CONN_STRING=postgres://postgres:saberviagens@postgres:5432/orders_db?sslmode=disable

  appcomida-api:
    build:
      context: ./backend/appcomida-api
      dockerfile: Dockerfile
    ports:
      - "4003:4003"
    environment:
      - DB_CONN_STRING=postgres://postgres:saberviagens@postgres:5432/appcomida_db?sslmode=disable

  appentrega-api:
    build:
      context: ./backend/appentrega-api
      dockerfile: Dockerfile
    ports:
      - "4004:4004"
    environment:
      - DB_CONN_STRING=postgres://postgres:saberviagens@postgres:5432/appentrega_db?sslmode=disable

  webrestaurante-api:
    build:
      context: ./backend/webrestaurante-api
      dockerfile: Dockerfile
    ports:
      - "4005:4005"
    environment:
      - DB_CONN_STRING=postgres://postgres:saberviagens@postgres:5432/webrestaurante_db?sslmode=disable

  delivery-api:
    build:
      context: ./backend/delivery-api
      dockerfile: Dockerfile
    ports:
      - "4006:4006"
    environment:
      - DB_CONN_STRING=postgres://postgres:saberviagens@postgres:5432/delivery_db?sslmode=disable

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: saberviagens
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
